// <auto-generated />
using System;
using LaboratoryTestRequestManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaboratoryTestRequestManagementSystem.Migrations
{
    [DbContext(typeof(LabDbContext))]
    partial class LabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Antibiotics",
                            Name = "Penicillin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Antibiotics",
                            Name = "Sulfa Drugs",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Environmental",
                            Name = "Latex",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Food",
                            Name = "Peanuts",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Food",
                            Name = "Shellfish",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Consumable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsumableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableName")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Consumables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsumableName = "EDTA Vacutainer (4ml)",
                            QuantityOnHand = 250,
                            ReorderLevel = 100,
                            Status = "Active",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            ConsumableName = "Sodium Citrate Tube (2.7ml)",
                            QuantityOnHand = 150,
                            ReorderLevel = 80,
                            Status = "Active",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            ConsumableName = "Microscope Slides",
                            QuantityOnHand = 500,
                            ReorderLevel = 200,
                            Status = "Active",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 4,
                            ConsumableName = "Wright-Giemsa Stain Kit",
                            QuantityOnHand = 25,
                            ReorderLevel = 10,
                            Status = "Active",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 5,
                            ConsumableName = "PT/INR Test Strips",
                            QuantityOnHand = 80,
                            ReorderLevel = 50,
                            Status = "Active",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 6,
                            ConsumableName = "Haemoglobin Electrophoresis Buffer",
                            QuantityOnHand = 12,
                            ReorderLevel = 5,
                            Status = "Active",
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.DoctorPatientAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("SharedTestRequestIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("DoctorPatientAccesses");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EmailVerificationTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HPCSANumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<string>("IsTwoFactorEnabled")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("MustChangePassword")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetPin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPinExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAIDNumber")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("TwoFactorRecoveryCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HPCSANumber")
                        .IsUnique()
                        .HasFilter("[HPCSANumber] IS NOT NULL AND [Role] = 'Doctor'");

                    b.HasIndex("SAIDNumber")
                        .IsUnique()
                        .HasFilter("[SAIDNumber] IS NOT NULL AND [Role] = 'LabTechnician'");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@nmbhlabsys.co.za",
                            FailedAttempts = 0,
                            FailedLoginAttempts = 0,
                            FirstName = "System",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Administrator",
                            MustChangePassword = "True",
                            PasswordHash = "Temp123!",
                            Role = "Admin",
                            Username = "admin@nmbhlabsys.co.za"
                        },
                        new
                        {
                            Id = 2,
                            Email = "labmanager@nmbhlabsys.co.za",
                            FailedAttempts = 0,
                            FailedLoginAttempts = 0,
                            FirstName = "Lab",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Manager",
                            MustChangePassword = "True",
                            PasswordHash = "Temp123!",
                            Role = "LaboratoryManager",
                            Username = "labmanager@nmbhlabsys.co.za"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "0821112222",
                            Email = "dr.doe@nmbhlabsys.co.za",
                            FailedAttempts = 0,
                            FailedLoginAttempts = 0,
                            FirstName = "John",
                            HPCSANumber = "MP0123456",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Doe",
                            MustChangePassword = "True",
                            PasswordHash = "Temp123!",
                            Role = "Doctor",
                            Username = "dr.doe@nmbhlabsys.co.za"
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "0832223333",
                            Email = "tech.smith@nmbhlabsys.co.za",
                            EmployeeNumber = "TECH001",
                            FailedAttempts = 0,
                            FailedLoginAttempts = 0,
                            FirstName = "Jane",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Smith",
                            MustChangePassword = "True",
                            PasswordHash = "Temp123!",
                            Role = "LabTechnician",
                            SAIDNumber = "9001010123087",
                            Username = "tech.smith@nmbhlabsys.co.za"
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.MedicalCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.ToTable("MedicalConditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Endocrine",
                            Name = "Diabetes Mellitus Type 2",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cardiovascular",
                            Name = "Hypertension",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Respiratory",
                            Name = "Asthma",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Infectious Disease",
                            Name = "HIV",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Infectious Disease",
                            Name = "Tuberculosis",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Renal",
                            Name = "Chronic Kidney Disease",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Antidiabetic",
                            Name = "Metformin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Category = "ACE Inhibitor",
                            Name = "Lisinopril",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Bronchodilator",
                            Name = "Salbutamol Inhaler",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Statin",
                            Name = "Atorvastatin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Antiplatelet",
                            Name = "Aspirin",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsRead")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCancelled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsumableId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCancelled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrderItemStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellphoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("MustChangePassword")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SouthAfricanIdNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SouthAfricanIdNumber")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellphoneNumber = "0843334444",
                            DateOfBirth = new DateTime(1985, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.johnson@example.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Alice",
                            HomeAddress = "123 Main Street, Gqeberha",
                            IsActive = "Active",
                            LastName = "Johnson",
                            MustChangePassword = "True",
                            PasswordHash = "Temp123!",
                            SouthAfricanIdNumber = "8505050123088",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.PatientAllergy", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("PatientId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.ToTable("PatientAllergies");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.PatientCondition", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalConditionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("PatientId", "MedicalConditionId");

                    b.HasIndex("MedicalConditionId");

                    b.ToTable("PatientConditions");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.PatientMedication", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("PatientId", "MedicationId");

                    b.HasIndex("MedicationId");

                    b.ToTable("PatientMedications");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CollectedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReceivedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SampleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ReceivedById");

                    b.HasIndex("SampleTypeId");

                    b.HasIndex("TestRequestId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.SampleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.ToTable("SampleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Whole Blood",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Plasma",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Serum",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bone Marrow",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Urine",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierName")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactPerson = "Thabo Ndlovu",
                            EmailAddress = "thabo@medilab.co.za",
                            Status = "Active",
                            SupplierName = "MediLab Supplies"
                        },
                        new
                        {
                            Id = 2,
                            ContactPerson = "Priya Naidoo",
                            EmailAddress = "priya@biotech.co.za",
                            Status = "Active",
                            SupplierName = "BioTech Diagnostics"
                        },
                        new
                        {
                            Id = 3,
                            ContactPerson = "Johan van Wyk",
                            EmailAddress = "johan@labcare.co.za",
                            Status = "Active",
                            SupplierName = "LabCare Solutions"
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TechnicianTestType", b =>
                {
                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<int>("TestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("TechnicianId", "TestTypeId");

                    b.HasIndex("TestTypeId");

                    b.ToTable("TechnicianTestTypes");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("TestCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Full Blood Count",
                            Description = "Complete blood count with differential",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Coagulation Studies",
                            Description = "PT, aPTT, INR",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Peripheral Blood Film",
                            Description = "Morphology examination",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Bone Marrow Aspirate",
                            Description = "Bone marrow analysis",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Haemoglobin Electrophoresis",
                            Description = "Haemoglobin variants",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCancelled")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("TestRequests");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestRequestTestType", b =>
                {
                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.Property<int>("TestTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VerifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TestRequestId", "TestTypeId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("TestTypeId");

                    b.HasIndex("VerifiedById");

                    b.ToTable("TestRequestTestTypes");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsAbnormal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.Property<int>("TestTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("VerifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TestRequestId");

                    b.HasIndex("TestTypeId");

                    b.HasIndex("VerifiedById");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestReviewHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.Property<int>("TestTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TestRequestId");

                    b.HasIndex("TestTypeId");

                    b.ToTable("TestReviewHistories");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("NormalRangeMax")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("NormalRangeMin")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SampleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<int>("TestCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TurnaroundTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("UnitsOfMeasurement")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SampleTypeId");

                    b.HasIndex("TestCategoryId");

                    b.ToTable("TestTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NormalRangeMax = 16.0m,
                            NormalRangeMin = 12.0m,
                            SampleTypeId = 1,
                            Status = "Active",
                            TestCategoryId = 1,
                            TestName = "Haemoglobin",
                            TurnaroundTimeMinutes = 30,
                            UnitsOfMeasurement = "g/dL"
                        },
                        new
                        {
                            Id = 2,
                            NormalRangeMax = 11.0m,
                            NormalRangeMin = 4.0m,
                            SampleTypeId = 1,
                            Status = "Active",
                            TestCategoryId = 1,
                            TestName = "White Blood Cell Count",
                            TurnaroundTimeMinutes = 30,
                            UnitsOfMeasurement = "x10³/µL"
                        },
                        new
                        {
                            Id = 3,
                            NormalRangeMax = 450m,
                            NormalRangeMin = 150m,
                            SampleTypeId = 1,
                            Status = "Active",
                            TestCategoryId = 1,
                            TestName = "Platelet Count",
                            TurnaroundTimeMinutes = 30,
                            UnitsOfMeasurement = "x10³/µL"
                        },
                        new
                        {
                            Id = 4,
                            NormalRangeMax = 13.5m,
                            NormalRangeMin = 11.0m,
                            SampleTypeId = 2,
                            Status = "Active",
                            TestCategoryId = 2,
                            TestName = "Prothrombin Time (PT)",
                            TurnaroundTimeMinutes = 45,
                            UnitsOfMeasurement = "seconds"
                        },
                        new
                        {
                            Id = 5,
                            NormalRangeMax = 35.0m,
                            NormalRangeMin = 25.0m,
                            SampleTypeId = 2,
                            Status = "Active",
                            TestCategoryId = 2,
                            TestName = "Activated Partial Thromboplastin Time (aPTT)",
                            TurnaroundTimeMinutes = 45,
                            UnitsOfMeasurement = "seconds"
                        },
                        new
                        {
                            Id = 6,
                            SampleTypeId = 1,
                            Status = "Active",
                            TestCategoryId = 3,
                            TestName = "Peripheral Blood Smear Review",
                            TurnaroundTimeMinutes = 60
                        },
                        new
                        {
                            Id = 7,
                            SampleTypeId = 4,
                            Status = "Active",
                            TestCategoryId = 4,
                            TestName = "Bone Marrow Aspirate Analysis",
                            TurnaroundTimeMinutes = 120
                        },
                        new
                        {
                            Id = 8,
                            SampleTypeId = 1,
                            Status = "Active",
                            TestCategoryId = 5,
                            TestName = "Haemoglobin Electrophoresis",
                            TurnaroundTimeMinutes = 90,
                            UnitsOfMeasurement = "%"
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestTypeConsumable", b =>
                {
                    b.Property<int>("TestTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ConsumableId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("TestTypeId", "ConsumableId");

                    b.HasIndex("ConsumableId");

                    b.ToTable("TestTypeConsumables");

                    b.HasData(
                        new
                        {
                            TestTypeId = 1,
                            ConsumableId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 2,
                            ConsumableId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 3,
                            ConsumableId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 4,
                            ConsumableId = 2,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 4,
                            ConsumableId = 5,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 5,
                            ConsumableId = 2,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 5,
                            ConsumableId = 5,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 6,
                            ConsumableId = 3,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 6,
                            ConsumableId = 4,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 7,
                            ConsumableId = 3,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 7,
                            ConsumableId = 4,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 8,
                            ConsumableId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            TestTypeId = 8,
                            ConsumableId = 6,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("IsTrusted")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "UserId", "UserType")
                        .IsUnique();

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Consumable", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Supplier", "Supplier")
                        .WithMany("Consumables")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.DoctorPatientAccess", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Employee", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Patient", "Patient")
                        .WithMany("DoctorAccessGrants")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Order", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Supplier", "Supplier")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.OrderItem", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Consumable", "Consumable")
                        .WithMany("OrderItems")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consumable");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.PatientAllergy", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Allergy", "Allergy")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Patient", "Patient")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.PatientCondition", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.MedicalCondition", "MedicalCondition")
                        .WithMany("PatientConditions")
                        .HasForeignKey("MedicalConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Patient", "Patient")
                        .WithMany("PatientConditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCondition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.PatientMedication", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Medication", "Medication")
                        .WithMany("PatientMedications")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Patient", "Patient")
                        .WithMany("PatientMedications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Sample", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Employee", "ReceivedBy")
                        .WithMany()
                        .HasForeignKey("ReceivedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.SampleType", "SampleType")
                        .WithMany()
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.TestRequest", "TestRequest")
                        .WithMany("Samples")
                        .HasForeignKey("TestRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceivedBy");

                    b.Navigation("SampleType");

                    b.Navigation("TestRequest");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TechnicianTestType", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Employee", "Technician")
                        .WithMany("TechnicianTestTypes")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.TestType", "TestType")
                        .WithMany("TechnicianTestTypes")
                        .HasForeignKey("TestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestRequest", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Employee", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestRequestTestType", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Employee", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.TestRequest", "TestRequest")
                        .WithMany("TestRequestTestTypes")
                        .HasForeignKey("TestRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.TestType", "TestType")
                        .WithMany()
                        .HasForeignKey("TestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Employee", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Technician");

                    b.Navigation("TestRequest");

                    b.Navigation("TestType");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestResult", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.TestRequest", "TestRequest")
                        .WithMany()
                        .HasForeignKey("TestRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.TestType", "TestType")
                        .WithMany()
                        .HasForeignKey("TestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Employee", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TestRequest");

                    b.Navigation("TestType");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestReviewHistory", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Employee", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.TestRequest", "TestRequest")
                        .WithMany()
                        .HasForeignKey("TestRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.TestType", "TestType")
                        .WithMany()
                        .HasForeignKey("TestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("TestRequest");

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestType", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.SampleType", "SampleType")
                        .WithMany()
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.TestCategory", "TestCategory")
                        .WithMany("TestTypes")
                        .HasForeignKey("TestCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SampleType");

                    b.Navigation("TestCategory");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestTypeConsumable", b =>
                {
                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.Consumable", "Consumable")
                        .WithMany("TestTypeConsumables")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratoryTestRequestManagementSystem.Models.TestType", "TestType")
                        .WithMany("TestTypeConsumables")
                        .HasForeignKey("TestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumable");

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Allergy", b =>
                {
                    b.Navigation("PatientAllergies");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Consumable", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("TestTypeConsumables");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Employee", b =>
                {
                    b.Navigation("TechnicianTestTypes");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.MedicalCondition", b =>
                {
                    b.Navigation("PatientConditions");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Medication", b =>
                {
                    b.Navigation("PatientMedications");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Patient", b =>
                {
                    b.Navigation("DoctorAccessGrants");

                    b.Navigation("PatientAllergies");

                    b.Navigation("PatientConditions");

                    b.Navigation("PatientMedications");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.Supplier", b =>
                {
                    b.Navigation("Consumables");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestCategory", b =>
                {
                    b.Navigation("TestTypes");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestRequest", b =>
                {
                    b.Navigation("Samples");

                    b.Navigation("TestRequestTestTypes");
                });

            modelBuilder.Entity("LaboratoryTestRequestManagementSystem.Models.TestType", b =>
                {
                    b.Navigation("TechnicianTestTypes");

                    b.Navigation("TestTypeConsumables");
                });
#pragma warning restore 612, 618
        }
    }
}
